// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl_DgcUn_Egum1lV47RtC-pA0JdXWdrOU',
    appId: '1:428510500564:web:5f8f0836d42fc8ce4dcd41',
    messagingSenderId: '428510500564',
    projectId: 'mynotes-flutter-projects-1019',
    authDomain: 'mynotes-flutter-projects-1019.firebaseapp.com',
    storageBucket: 'mynotes-flutter-projects-1019.appspot.com',
    measurementId: 'G-2252LSWSV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRn0YSteqW91KcRcPrtS2_zYbZt5TWHYU',
    appId: '1:428510500564:android:56ced3768120c74b4dcd41',
    messagingSenderId: '428510500564',
    projectId: 'mynotes-flutter-projects-1019',
    storageBucket: 'mynotes-flutter-projects-1019.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeEusnuyo4Qn3D-jADkE5AahYmuyES_KU',
    appId: '1:428510500564:ios:ae80c71cff93fad14dcd41',
    messagingSenderId: '428510500564',
    projectId: 'mynotes-flutter-projects-1019',
    storageBucket: 'mynotes-flutter-projects-1019.appspot.com',
    iosBundleId: 'com.testing.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeEusnuyo4Qn3D-jADkE5AahYmuyES_KU',
    appId: '1:428510500564:ios:8cc7a900f87fb0ff4dcd41',
    messagingSenderId: '428510500564',
    projectId: 'mynotes-flutter-projects-1019',
    storageBucket: 'mynotes-flutter-projects-1019.appspot.com',
    iosBundleId: 'com.testing.mynotes.RunnerTests',
  );
}
